### PR TITLE
Add a setup script to change/adopt the templates

### PR DESCRIPTION
**Pull request by erpe**
a quick attempt to automate the tasks i have to do when using your great template ;)

### CODE REVIEW

**Comment by nikwen** [comment]
Thanks a lot for your pull request. This looks really nice!
Please give me a few days to review and test this. I'm quite busy at the moment but I will make sure I don't forget about this one. ;)

**Comment by erpe** [comment]
no hurry! ;)

**Comment by nikwen** [comment]
Thank you very much again for your pull request. The script works great. :)

Would you mind adding a (mandatory) option for changing the package name as well? It can be found in the files `manifest.json` and `share/forum-app/main.qml` and didn't change when running the script. I noticed that the template still uses the old naming scheme, so I'll change that now and we'll only need an option asking for the developer's application namespace.

Otherwise the script looks fine and I'd be happy to merge it with these changes. Good job! :)

**Comment by nikwen** [comment]
Here's the change: https://github.com/nikwen/ubuntu-go-qml-template/commit/e1248e38f3b11ba8bab2d1dd7e232237490b3fcd ;)

**Comment by erpe** [comment]
sure - will have a look at it today...
;)

**Comment by erpe** [comment]
... guess this should do the trick now...  :yum:

**Comment by nikwen** [comment]
Thanks! This would probably work most times now. However, it might break when the entered email address contains the phrase "nikwen" (like mine). ;)

I'd suggest adding the following code before line 118 (and removing line 122):

``` ruby
if fname == 'manifest.json' || fname == 'share/forum-app/main.qml'
  changed = text.gsub(/ubuntu-go-qml-template.nikwen/, "#{@options.name}.#{@options.namespace}")
end
```

As I've never coded in Ruby before, please check that code for correctness. It could be that we have to escape the dot in the gsub string for example.

**Comment by erpe** [comment]
my fault - checked against wrong option name - but for sure nikwen can be used ;)
i'll have a look at your proposal...

**Comment by erpe** [comment]
finally - cleaned up.

**Comment by nikwen** [comment]
Looks good, thanks! :)
Just let me test it once again. ;)

**Comment by nikwen** [comment]
Works perfectly fine. Thank you very much again! :+1: :smile:

**Pull request merged**
