### PR TITLE
add option to select go version, adopt scripts and rename install-go-…

### PR DESCRIPTION
**Pull request by erpe**
added an option to specify go-version with setup.rb.
a.t.m. there is only 1.3.3 and 1.4.3 usable - default is 1.4.3.
i still need to fiddle around with GOROOT_BOOTSTRAP... for go1.5
have a nice day... ;)

### CODE REVIEW

**Comment by nikwen** [comment]
Thank you very much for this pull request!

I had a quick look at it and it should probably work fine. I'm currently just thinking about whether it would be better to pass the go version as a parameter to the installation script instead. On the one hand that would definitely be less error-prone in the future. That's why I'm thinking about it. On the other hand this would, however, have the drawbacks of either requiring us to put another file in there containing the preferred Go version or making it harder for other people to use the same build environment as the project maintainer of a specific software built on top of this does. (One would always have to specify the go version while setting up the chroot.)

What are your thoughts on this? Are there any arguments I missed?

Thanks again! :)

PS: I don't want to convince you to change anything at the moment. I'm simply wondering what your thoughts on this are. ;)

**Comment by erpe** [comment]
while thinkin about it i'm wondering why at all the go version should be configurable (who the hell came up with this idea anyway :)
at least for go with major version 1 we could always use latest stable and all golang-code of the templated project should just work fine -  supposed to be backwards compatible (see: https://golang.org/doc/go1compat). the downside would be the need(?) to stay in line with go releases ...
summarized: why not keep a supplied install-go.sh with fixed version and forget about the configurable go-version story? 
perhaps we're trying to solve problems that are'nt existing yet?

:see_no_evil:

**Comment by nikwen** [comment]
Hi again,

I thought about this for a while. I really do think that it makes sense to make the version configurable as it will allow users to use a new Go version, even if we haven't updated the template yet. In that case, I would like to word the comment "one out of: 1.3.3 || 1.4.3" as "for example: 1.33 || 1.4.3" though. What do you think about that?
By the way, I have indeed seen cases where a new Go version breaks stuff. It happens every time when Ubuntu releases a new Go version into its archives. ;)
That's why I'd still prefer merging this.

What are your thoughts on this?

Thank you very much in advance. :)

(PS: I'm a bit busy at the moment. Please bear with me if it takes me a few days to reply. :wink:)

**Comment by erpe** [comment]
:) hi there - 
your approach to allow any go version sounds quite reasonable. (i was hoping to manage to avoid the different build procedures for prior and after go1.5. )
i'll rework this PR to match your idea.

/me busy also - so this takes a couple days ...

**Comment by erpe** [comment]
:santa: made it happen...

**Comment by nikwen** [comment]
Hi,

thanks a lot for working on this! I looked through the code and it looks really good. It will take some days until I have access to my Ubuntu machine again but I will definitely review it as soon as I have.

Thanks again. :)

**Comment by nikwen** [comment]
So I finally came around to reviewing this. :)
I'm really sorry that it took so long! I'm just busy with real life stuff ...

Now to your code. Really well done! :smile:

However, installing Go doesn't seem to work for me. I get the following error message when running `chroot-scripts/setup-chroot.sh`:

Image
("Zeile" is German for "line" and "Datei oder Verzeichnis nicht gefunden" means "File or directory could not be found".)

I guess that the Go installation is for some reason not in that directory by default, at least in Ubuntu 15.04. The [documentation](https://golang.org/doc/install/source) recommends `GOROOT_BOOTSTRAP=/usr` for vivid but that doesn't work for me either. "Cannot find package" errors ... The reason for that seems to be that compiling 1.5.2 requires Go >=1.4 while Ubuntu 15.04 ships with 1.3.3.

Which brings me to the following question: Did you install a custom Go version on your machine or do you use the one from the Ubuntu archives? And what Ubuntu version do you use? If you can confirm that you use the wily archive version and that it works for you this way, we could put a check into the install script so that it installs Go 1.3.3 on Ubuntu <=15.04 and Go 1.5.2 (or the custom version) on Ubuntu 15.10 and upwards. Besides Ubuntu 14.04, nobody (including me) should continue to use Ubuntu <=15.04 after the end of support on Feb 4 anyway.

What do you think?

Besides that, there are just two other things I noticed. ;)
- In `gsub_files` we check if the files that we want to modify actually exist. Since this PR renames the install script, I think it would be useful to have something similar in `adopt_go_version` as well. :)
- Minor formatting stuff :stuck_out_tongue:: I'd prefer having the help text for the new option being more in line with the other ones. What do you think about "The Go version to install in the chroot" and "Default is Go 1.5.2"?
  Additionally, would you mind fixing the indentation in the screenshot below? :)
  Image

Despite this long wall of text, I really like your pull request. Thanks a lot for it! :)

And I'll try to respond faster next time! :wink: 

Cheers,
Niklas

**Comment by erpe** [comment]
i'll fix/inspect that asap...

bis dahin... ;)
rene

**Comment by nikwen** [comment]
Great. Thanks! :)

**Pull request closed without merging**
